export const env = `
APP_NAME="iHold Bank"
APP_ENV=local
APP_KEY=base64:GUB6cwtW0hvC6GnoEbvlw7AUH1PGEbyXxAK9oC0AZOY=
APP_DEBUG=true
APP_URL=http://example-app.test

LOG_CHANNEL=stack
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=banking_system
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

MEMCACHED_HOST=memcached

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=sandbox.smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=8d73f14b8829e2
MAIL_PASSWORD=b1c9bc38b4b1a1
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS="twins@inbound.devmail.email"
MAIL_FROM_EMAIL="twins@inbound.devmail.email"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_HOST=banking_app
PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

DOCKER_NGINX_PORT=8080
DOCKER_DB_PORT=5432
DOCKER_XDEBUG_PORT=docker.for.mac.localhost #add your docker network IP, for MacOs use: docker.for.mac.localhost
DOCKER_PUSHER_APP_PORT=6001
DOCKER_REDIS_PORT=6379

SENDGRID_API_KEY=

#Bankly
BANKLY_BRANCH_ACC=
BANKLY_ACCOUNT_ACC=
BANKLY_COMPANY_KEY=
BANKLY_DOCUMENT_ACC=
BANKLY_CREDENTIALS=
BANKLY_SLEEP_TIME_REQUEST=1000000
BANKLY_REQUEST_INTERVAL=10
BANKLY_HTTP_RATE_LIMIT=170
BANKLY_CACHE_TOKEN_TIME=3600
BANKLY_PROGRAM_ID_PHYSICAL=
BANKLY_PROGRAM_ID_VIRTUAL=
BANKLY_TOKEN_SCOPE=
BANKLY_WEBHOOKS_PUBLIC_KEY=4444
BANKLY_WEBHOOKS_PRIVATE_KEY=

#IDENTITY SERVER
TOKEN_SECRET=
IDENTITY_SERVER_URL=

#GCSM
GOOGLE_CERTIFICATES_PATH=''
GOOGLE_CLOUD_SECRET_PROJECT_ID=''
GOOGLE_CLOUD_SECRET_CERT_NAME=''
GOOGLE_CLOUD_SECRET_CERT_KEY=''
GOOGLE_CLOUD_SECRET_BANKLY_CERT_PASSPHRASE=''
GOOGLE_CLOUD_SECRET_BANKLY_DYNAMIC_CLIENT_ID=''
#GCS
GOOGLE_CLOUD_PROJECT_ID=''
GOOGLE_CLOUD_STORAGE_BUCKET=''
#GCS CREDENTIALS
GOOGLE_CLOUD_ACCOUNT_TYPE=
GOOGLE_CLOUD_PRIVATE_KEY_ID=
GOOGLE_CLOUD_PRIVATE_KEY=
GOOGLE_CLOUD_CLIENT_EMAIL=
GOOGLE_CLOUD_CLIENT_ID=
GOOGLE_CLOUD_AUTH_URI=
GOOGLE_CLOUD_TOKEN_URI=
GOOGLE_CLOUD_AUTH_PROVIDER_CERT_URL=
GOOGLE_CLOUD_CLIENT_CERT_URL=
#GOOGLE KMS
GOOGLE_KMS_LOCATION=
GOOGLE_KMS_KEY_RING=
GOOGLE_KMS_KEY=

#FIREBASE CREDENTIALS
FIREBASE_CLOUD_PROJECT_ID=
FIREBASE_CLOUD_ACCOUNT_TYPE=
FIREBASE_CLOUD_PRIVATE_KEY_ID=
FIREBASE_CLOUD_PRIVATE_KEY=
FIREBASE_CLOUD_CLIENT_EMAIL=
FIREBASE_CLOUD_CLIENT_ID=
FIREBASE_CLOUD_AUTH_URI=
FIREBASE_CLOUD_TOKEN_URI=
FIREBASE_CLOUD_AUTH_PROVIDER_CERT_URL=
FIREBASE_CLOUD_CLIENT_CERT_URL=
FIREBASE_AUTO_DISCOVERY=

#TWILIO
TWILIO_SID=
TWILIO_TOKEN=
TWILIO_PHONE_NUMBER=
TWILIO_CALLBACK=

#OTP
OTP_VALIDITY_TIME=3
OPT_LENGTH=6
OTP_ALLOWED_ATTEMPTS=10
OTP_MAXIMUM_OTPS_ALLOWED=1
OTP_DELETE_OLD_OTPS=3

#SWAGGER
L5_ROUTE_API=""

#SENTRY
SENTRY_LARAVEL_DSN=""
SENTRY_TRACES_SAMPLE_RATE=""

# PROCOB
PROCOB_USER=
PROCOB_PASSWORD=

#WHITE-LABEL DOMAIN ENV VARS
API_DOMAIN=''
API2_DOMAIN=''
WEBHOOK_DOMAIN=''
FULL_DOMAIN=''

# ADIQ
ADIQ_LOGIN_URL=
ADIQ_API_URL=
# ADIQ - ENVIRONMENT DEV
ADIQ_USERNAME=
ADIQ_PASSWORD=
# ADIQ - GSM
GOOGLE_CLOUD_SECRET_ADIQ_USERNAME=
GOOGLE_CLOUD_SECRET_ADIQ_PASSWORD=`;
